apiVersion: v1
kind: Service
metadata:
  name: clippr-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: 80
      name: http
  selector:
    app: clippr-frontend
