{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clippr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: clippr-backend
                port:
                  number: {{ $.Values.service.backendPort }}
          - path: /identity(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: clippr-identityservice
                port:
                  number: {{ $.Values.service.identityServicePort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clippr-frontend
                port:
                  number: {{ $.Values.service.frontendPort }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}