services:
  identity_debug:
    container_name: clippr_identity
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      target: debug
    environment:
      - ConnectionStrings__Default=Server=database;Database=clipprIdentityDb;Uid=root;
      - Hosting__Url=https://clippr_reverse_proxy:8080/identity
      - Authentication__ExternalProviders__0__ProviderKey=${Authentication__ExternalProviders__0__ProviderKey}
      - Authentication__ExternalProviders__0__Issuer=${Authentication__ExternalProviders__0__Issuer}
      - Authentication__ExternalProviders__0__Audience=${Authentication__ExternalProviders__0__Audience}
