services:
  identity_debug:
    profiles:
      - debug
    container_name: clippr_identity
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      target: debug
    environment:
      - ConnectionStrings__Default=Server=database;Database=clipprIdentityDb;Uid=root;
      - Hosting__Url=http://localhost:8080/identity

  identity_prod:
    profiles:
      - prod
    container_name: clippr_identity
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      target: debug
    environment:
      - ConnectionStrings__Default=Server=database;Database=clipprIdentityDb;Uid=root;
      - Hosting__Url=http://localhost:8080/identity
