services:
  backend_debug:
    profiles:
      - debug
    container_name: clippr_backend
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      target: debug
    environment:
      - ConnectionStrings__Default=Server=database;Database=clipprDb;Uid=root;
      - Authentication__Authority=${Authentication__Authority}
      - Authentication__ClientId=${Authentication__ClientId}

  backend_prod:
    profiles:
      - prod
    container_name: clippr_backend
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      target: debug
    environment:
      - ConnectionStrings__Default=Server=database;Database=clipprDb;Uid=root;
      - Authentication__Authority=${Authentication__Authority}
      - Authentication__ClientId=${Authentication__ClientId}

  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database:
