include:
  - ../backend/docker-compose.yaml
  - ../frontend/docker-compose.yaml
  - ../identityService/docker-compose.yaml

services:
  reverse_proxy_debug:
    image: nginx:latest
    container_name: clippr_reverse_proxy
    depends_on:
      - backend_debug
      - frontend_debug
    ports:
      - 8080:8080
    volumes:
      - ./nginx:/etc/nginx/:ro
