include:
  - ../backend/docker-compose.yaml
  - ../frontend/docker-compose.yaml
  - ../identityService/docker-compose.yaml

services:
  reverse_proxy_debug:
    image: nginx:latest
    container_name: clippr_reverse_proxy
    depends_on:
      - backend_debug
      - frontend_debug
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/:ro
    profiles:
      - debug
  reverse_proxy_prod:
    image: nginx:latest
    container_name: clippr_reverse_proxy
    depends_on:
      - backend_prod
      - frontend_prod
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/:ro
    profiles:
      - prod
