apiVersion: v2
name: clippr
description: Helm chart for deploying the clippr web clipboard application
type: application
version: 0.1.2
appVersion: "1.0"
dependencies:
  - name: mariadb
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
