image:
  frontend: ghcr.io/simonfranken/clippr-frontend:main
  backend: ghcr.io/simonfranken/clippr-backend:main
  identityService: ghcr.io/simonfranken/clippr-identity:main

replicaCount: 1

service:
  type: ClusterIP
  frontendPort: 80
  backendPort: 80
  identityServicePort: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: "clippr.example.com"
  tls:
    enabled: true
    secretName: clippr-tls

config:
  backendEnv: {}
  identityServiceEnv: {}
  frontendEnv: {}

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: "changeme"
    password: "changeme"
  primary:
    persistence:
      enabled: true
      size: 8Gi
